"""Constants for Project Cyder."""

DOMAIN = "cyd_ha_monitor"
ESPHOME_DOMAIN = "esphome"

CONF_DEVICE_ID = "device_id"
CONF_RULES = "rules"
CONF_DASHBOARD_SETTINGS_SAVED = "dashboard_settings_saved"
CONF_MAIN_POWER_ENTITY = "main_power_entity"
CONF_DAILY_ENERGY_ENTITY = "daily_energy_entity"
CONF_CLIMATE_ENTITY = "climate_entity"
CONF_ROOM_ENTITIES = "room_entities"
CONF_CAMERA_ENTITY = "camera_entity"
CONF_AUTO_ROTATION = "auto_rotation"
CONF_ROTATION_INTERVAL = "rotation_interval"
CONF_CAMERA_REFRESH_INTERVAL = "camera_refresh_interval"
CONF_SHOW_AI_PAGE = "show_ai_page"
CONF_SHOW_CLIMATE_PAGE = "show_climate_page"
CONF_SHOW_SENSORS_PAGE = "show_sensors_page"
CONF_SHOW_ENERGY_PAGE = "show_energy_page"
CONF_SHOW_CAMERA_PAGE = "show_camera_page"
CONF_ROTATION_PAGE_1 = "rotation_page_1"
CONF_ROTATION_PAGE_2 = "rotation_page_2"
CONF_ROTATION_PAGE_3 = "rotation_page_3"
CONF_ROTATION_PAGE_4 = "rotation_page_4"
CONF_ROTATION_PAGE_5 = "rotation_page_5"
CONF_ROTATION_PAGE_6 = "rotation_page_6"
CONF_POWER_METRICS = "power_metrics"
CONF_SENSOR_METRICS = "sensor_metrics"
CONF_METRIC_ENTITY_ID = "entity_id"
CONF_METRIC_NAME = "name"
CONF_CLAUDE_SESSION_ENTITY = "claude_session_entity"
CONF_CLAUDE_WEEK_ENTITY = "claude_week_entity"
CONF_CLAUDE_SESSION_RESET_ENTITY = "claude_session_reset_entity"
CONF_CLAUDE_WEEK_RESET_ENTITY = "claude_week_reset_entity"
CONF_CLAUDE_EXTRA_USED_ENTITY = "claude_extra_used_entity"
CONF_CLAUDE_EXTRA_LIMIT_ENTITY = "claude_extra_limit_entity"
CONF_CLAUDE_EXTRA_PERCENT_ENTITY = "claude_extra_percent_entity"
CONF_CLAUDE_EXTRA_MODE = "claude_extra_mode"
CONF_AI_PROVIDERS = "ai_providers"
CONF_PROVIDER_NAME = "provider_name"
CONF_PROVIDER_SESSION_ENTITY = "session_entity"
CONF_PROVIDER_WEEK_ENTITY = "week_entity"
CONF_PROVIDER_SESSION_RESET_ENTITY = "session_reset_entity"
CONF_PROVIDER_WEEK_RESET_ENTITY = "week_reset_entity"
CONF_CODEX_NAME = "codex_name"
CONF_CODEX_SESSION_ENTITY = "codex_session_entity"
CONF_CODEX_WEEK_ENTITY = "codex_week_entity"

CONF_ENTITY_ID = "entity_id"
CONF_DIRECTION = "direction"
CONF_THRESHOLD = "threshold"
CONF_HYSTERESIS = "hysteresis"
CONF_PRIORITY = "priority"
CONF_TITLE = "title"
CONF_MESSAGE = "message"
CONF_ATTENTION_PAGE = "attention_page"
ATTENTION_PAGE_VALUES = (
    "none", "home", "ai", "climate", "sensors", "energy", "camera"
)

ACTION_DISPLAY_ALERT = "display_alert"
ACTION_CLEAR_ALERT = "clear_alert"
ACTION_DISMISS_ALERT = "dismiss_alert"
ACTION_UPDATE_DASHBOARD = "update_dashboard"
ACTION_FOCUS_PAGE = "focus_page"

ISSUE_ACTIONS_UNAVAILABLE = "actions_unavailable"
ISSUE_DASHBOARD_ACTION_UNAVAILABLE = "dashboard_action_unavailable"
ISSUE_FOCUS_PAGE_ACTION_UNAVAILABLE = "focus_page_action_unavailable"
