"""Constants for Project Cyder."""

DOMAIN = "cyd_ha_monitor"
ESPHOME_DOMAIN = "esphome"

CONF_DEVICE_ID = "device_id"
CONF_RULES = "rules"
CONF_DASHBOARD_SETTINGS_SAVED = "dashboard_settings_saved"
CONF_MAIN_POWER_ENTITY = "main_power_entity"
CONF_DAILY_ENERGY_ENTITY = "daily_energy_entity"
CONF_POWER_METRICS = "power_metrics"
CONF_METRIC_ENTITY_ID = "entity_id"
CONF_METRIC_NAME = "name"
CONF_CLAUDE_SESSION_ENTITY = "claude_session_entity"
CONF_CLAUDE_WEEK_ENTITY = "claude_week_entity"
CONF_CLAUDE_EXTRA_USED_ENTITY = "claude_extra_used_entity"
CONF_CLAUDE_EXTRA_LIMIT_ENTITY = "claude_extra_limit_entity"
CONF_CLAUDE_EXTRA_PERCENT_ENTITY = "claude_extra_percent_entity"
CONF_CLAUDE_EXTRA_MODE = "claude_extra_mode"

CONF_ENTITY_ID = "entity_id"
CONF_DIRECTION = "direction"
CONF_THRESHOLD = "threshold"
CONF_HYSTERESIS = "hysteresis"
CONF_PRIORITY = "priority"
CONF_TITLE = "title"
CONF_MESSAGE = "message"

ACTION_DISPLAY_ALERT = "display_alert"
ACTION_CLEAR_ALERT = "clear_alert"
ACTION_DISMISS_ALERT = "dismiss_alert"
ACTION_UPDATE_DASHBOARD = "update_dashboard"

ISSUE_ACTIONS_UNAVAILABLE = "actions_unavailable"
ISSUE_DASHBOARD_ACTION_UNAVAILABLE = "dashboard_action_unavailable"
